### ISSUE TITLE
Requests for Auto-Pause

### ISSUE THREAD

**Issue by Endarire** [FakeFriend24/pfk-auto-pauser#4]
@FakeFriend24 
Thankee for your work so far on this mod!  I also request these options.

-Enable auto-pause when local area map screen is displayed.

-Enable auto-pause after inventory/character screen closes.

**Comment by FakeFriend24** [comment]
added in 0.2.0, but auto pauses when screens are **opened**, cause Pause cant  be overwritten when you're already in Menu. But should not make any difference.
