### ISSUE TITLE
Auto-Pauser BUG and Requests 2 2 22

### ISSUE THREAD

**Issue by Endarire** [FakeFriend24/pfk-auto-pauser#5]
@FakeFriend24 
Greetings, JesusLives!

Today I learned that the auto-pauser was the reason I couldn't enter camp on the overworld.  I only had Auto-Pause on Area Load active.  Even disabling all auto-pause options didn't fix the problem:  Only disabling the mod and restarting the game did.

Request: Add an auto-pause option: Auto-Pause when Container Opened.  I don't like how my buffs continue ticking down when opening a chest or a plant or somesuch, though I've adjusted to quickly manually pausing.

Thankee!

**Comment by FakeFriend24** [comment]
should be fixed, missing check for Areaload on Globalmap, could not recreate it after adding that.

Also: request done.
